### ISSUE TITLE
Link for gaze files no longer works

### ISSUE THREAD

**Issue by luca-vm** [asaran/IL-CGL#1]
Hi in the readme:

Download the pretrained [gaze models](https://drive.google.com/file/d/1tSQsMpPt354r69-ebHSQwQ3mjxkzKL6v/view?usp=sharing) (trained on all demos except the high-score ones for each game) and store them inside the data/trained_gaze_models/ folder.

The google drive link no longer works. I have been attempting to train the gaze models myself for my research but have been bogged down with errors for many days, mostly due to the legacy tensorflow version.

If it would not be too much of a hassel could you update the google drive link.

![image](https://github.com/user-attachments/assets/75fb33ba-f2f3-4f90-8468-4ef392ad88ba)

**Comment by asaran** [comment]
Thanks for pointing this out. The link for the pretrained model has been updated.
