### ISSUE TITLE
.hdf5 file for human_gaze not in repo

### ISSUE THREAD

**Issue by luca-vm** [asaran/IL-CGL#2]
In this part of the human_gaze.py:
if __name__ == "__main__":
    from load_data import *
    d = Dataset(sys.argv[1], sys.argv[2]) #tarfile (images), txtfile (labels)
    # For gaze prediction
    d.generate_data_for_gaze_prediction()
     gp = Human_Gaze_Predictor(sys.argv[3]) #game name
    gp.init_model(sys.argv[4]) `#gaze model .hdf5 file provided in the repo`
    gp.predict_and_save(d.gaze_imgs)

    
    
    Where are these files?

**Comment by asaran** [comment]
The link for the pretrained model has been updated.
